// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkujqrlnowqvanfsgtvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdWpxcmxub3dxdmFuZnNndHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjgzOTUsImV4cCI6MjA2MTI0NDM5NX0.O9J-RRLBYGCu67qQ4q_mcMNnDmdT5iwH9XDmVhra-S8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);